// src/core/notebook-solid.tsx
import { Component, createSignal, onCleanup, onMount } from "solid-js";
import type { Accessor, Setter } from "solid-js";
import { Notebook } from "./notebook-core";

export interface Cell {
  id: string;
  type: "code";
  content: string;
  output?: {
    result: any;
    logs: string[];
  };
  error?: string;
  analysis?: {
    exports: Array<{ name: string; value: any; type: string }>;
    references: Array<{ name: string; count: number }>;
  };
}

export interface NotebookState {
  cells: Cell[];
  focusedCellId: string | null;
  globals: Record<string, any>;
}

interface NotebookProps {
  class?: string;
  state: Accessor<NotebookState>;
  setState: Setter<NotebookState>;
}

export const NotebookComponent: Component<NotebookProps> = (props) => {
  const [ref, setRef] = createSignal<HTMLDivElement>();
  let notebookInstance: Notebook | undefined;

  onMount(() => {
    const container = ref();
    if (!container) return;

    const notebook = new Notebook({
      initialState: props.state(),
      onChange: (newState) => {
        props.setState(() => newState);
      },
    });

    const cleanup = notebook.mount(container);
    notebookInstance = notebook;

    onCleanup(() => {
      cleanup();
      notebookInstance = undefined;
    });
  });

  return (
    <div
      ref={setRef}
      class={props.class}
      style={{ width: "100%", height: "100%" }}
    />
  );
};

// src/core/notebook-react.tsx
import { Observable, observable } from "@legendapp/state";
import React, { useEffect, useRef } from "react";
import { NotebookState, Notebook as VanillaNotebook } from "./notebook-vanilla";

interface NotebookProps {
  className?: string;
  initialState?: Partial<NotebookState>;
  state$?: Observable<NotebookState>;
}

export const NotebookComponent = ({
  className,
  initialState,
  state$,
}: NotebookProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const notebookRef = useRef<VanillaNotebook | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    const notebook = new VanillaNotebook({
      state$:
        state$ ||
        observable<NotebookState>({
          cells: initialState?.cells || [],
          focusedCellId: initialState?.focusedCellId || null,
          globals: initialState?.globals || {},
        }),
    });

    const cleanup = notebook.mount(containerRef.current);
    notebookRef.current = notebook;

    return () => {
      cleanup();
      notebookRef.current = null;
    };
  }, []);

  return (
    <div
      ref={containerRef}
      className={className}
      style={{ width: "100%", height: "100%" }}
    />
  );
};
